# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: verilator/verilator
    strategy:
      matrix:
        node-version: [12.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '3.16.x'
    - name: Use cmake
      run: cmake --version
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: make
    - run: make VERILATOR_USER_ARGS=-DEB0
    - run: git clone https://github.com/ameetgohil/elastic-signalflip-example.git elastic && rm -rf elastic/.git
    - run: cd elastic
    - run: npm i
    - run: make
    - run: cd ..
    - run: git clone https://github.com/ameetgohil/basic-signalflip-example.git basic && rm -rf basic/.git
    - run: cd basic
    - run: npm i
    - run: make
    - run: cd ..
    - run: git clone https://github.com/ameetgohil/APB3-config-regs.git
    - run: cd APB3-config-regs/sim
    - run: npm i
    - run: make
    - run: cd ../..
    - run: git clone https://github.com/ameetgohil/leading-zeroes-counter.git
    - run: cd leading-zeroes-counter/sim
    - run: npm i
    - run: make
    - run: cd ../..
    - run: git clone --recursive https://github.com/ameetgohil/reciprocal-sv.git
    - run: cd reciprocal-sv/sim
    - run: npm i
    - run: make
    

